# Site settings
author: Tanajah Rosenbaum
title: 
header-img: img/home-bg.png
email: tanajahr25@gmail.com
copyright_name: Tanajah Rosenbaum
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tanajahr25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
